---
# This playbook deploys the whole application stack in this site.

- name: Apply common configuration to all nodes
  hosts: linux 
  become: yes

  roles:
    - common

- name: Configure and deploy the webservers and application code
  hosts: linux
  become: yes

  roles:
    - web

- name: Deploy MariaDB and configure the databases
  hosts: linux
  become: yes

  roles:
    - db
