---
mariadb_packages_rh:
   - mariadb-server
   - python3-PyMySQL
     #- libselinux-python
     #- libsemanage-python

mariadb_packages_db:
   - mariadb-server
   - python3-mysqldb
     #- libselinux-python
     #- libsemanage-python
   - python3-selinux
   - python3-semanage

mariadb_port: 3306
mariadb_datadir: /var/lib/mysql
mariadb_socket: /var/lib/mysql/mysql.sock
mariadb_user: mariadb
mariadb_symbolic_links: 0
mariadb_log_error: /var/log/mysql/mariadb.err
mariadb_pid_file: /var/run/mysqld/mariadb.pid

mariadb_dbname: obligatorio
mariadb_dbuser: obligatorio
mariadb_upassword: ansible
