---
# These tasks install http and the php modules.

- name: Install http and php etc on RedHat servers
  yum:
    name: "{{ item }}"
    state: latest
  loop: "{{ packages_rh }}"
  when: ansible_os_family == "RedHat"

- name: Install http and php etc on Debian servers
  apt:
    name: "{{ item }}"
    state: latest
  loop: "{{ packages_db }}"
  when: ansible_os_family == "Debian"

- name: Check if Apache is running
  service:
    name: httpd
    state: started

- name: Open port 80 on firewall for RedHat servers
  firewalld:
    service: http
    permanent: yes
    state: enabled
    immediate: yes
  when: ansible_os_family == "RedHat"
  notify: restart firewalld

- name: Open port 80 on firewall for Debian servers
  ufw:
    rule: allow
    port: "80"
    proto: tcp
  when: ansible_os_family == "Debian"

- name: http service state
  service:
    name: httpd
    state: started
    enabled: yes

    #- name: Configure SELinux to allow httpd to connect to remote database
  #seboolean:
  #  name: httpd_can_network_connect_db
  #  state: true
  #  persistent: yes
  #when: sestatus.rc != 0
