---
# This playbook contains common plays that will be run on all nodes.

- name: Install ntp on RedHat servers
  yum:
    name: chrony.x86_64 
    state: latest
  when: ansible_os_family == "RedHat"
  tags: ntp

- name: Install ntp on Debian servers
  apt:
    name: ntp
    state: latest
  when: ansible_os_family == "Debian"
  tags: ntp

- name: Configure ntp file on RedHat servers
  template:
    src: ntp.conf.j2
    dest: /etc/ntp.conf
  when: ansible_os_family == "RedHat"
  tags: ntp
  notify: restart ntp_rh

- name: Configure ntp file on Debian servers
  template:
    src: ntp.conf.j2
    dest: /etc/ntp.conf
  when: ansible_os_family == "Debian"
  tags: ntp
  notify: restart ntp_db

- name: Start the ntp service on RedHat servers
  service:
    name: chronyd 
    state: started
    enabled: yes
  when: ansible_os_family == "RedHat"
  tags: ntp

- name: Start the ntp service on Debian servers
  service:
    name: ntp.service
    state: started
    enabled: yes
  when: ansible_os_family == "Debian"
  tags: ntp

- name: Set SELinux current mode to enforcing on RedHat servers
  selinux:
    policy: targeted
    state: enforcing
  when: ansible_os_family == "RedHat" 

