---
# This playbook contains common plays that will be run on all nodes.

- name: Install ntp on RedHat servers
  yum:
    name: chrony.x86_64 
    state: latest
  when: ansible_os_family == "RedHat"
  tags: ntp

- name: Install ntp on Debian servers
  apt:
    name: ntp
    state: latest
  when: ansible_os_family == "Debian"
  tags: ntp

- name: Configure ntp file
  template:
    src: ntp.conf.j2
    dest: /etc/ntp.conf
  tags: ntp
  notify: restart ntp

- name: Start the ntp service
  service:
    name: ntpd
    state: started
    enabled: yes
  tags: ntp

- name: Install SELinux on Debian servers
  apt:
    name: "{{ item }}"
    state: latest
  loop: "{{ selinux }}"  
  when: ansible_os_family == "Debian"
  tags: selinux

- name: Enable SELinux on Debian server
  command: selinux-activate
  when: ansible_os_family == "Debian"

- name: Set SELinux current mode to enforcing on RedHat servers
  selinux:
    policy: targeted
    state: enforcing
  when: ansible_os_family == "RedHat" 

- name: Set SELinux current mode to enforcing on Debian server
  command: selinux-config-enforcing
  when: ansible_os_family == "Debian"
 
